### ISSUE TITLE
Can't retrieve layer progress! After after update to 1.25.1

### ISSUE THREAD

**Issue by Boxter83** [OllisGit/OctoPrint-DisplayLayerProgress#204] opened 2021-01-31 10:37 UTC
![16120892816461537463762056324827](https://user-images.githubusercontent.com/36458024/106381341-58ce9d00-63b8-11eb-9a29-656ca8d53933.jpg)

I have 3 printers with all the same problem after update the plug-in to 1.25.1 version.

**Comment by sebbl2** [comment] 2021-01-31 10:50
Same here (Prusa MK3s)

**Comment by OllisGit** [comment] 2021-01-31 11:10
Hi @sebbl2 ,

thanks for reporting. It is now fixed in Version 1.25.2

BR
Olli

**Comment by adrensnyder** [comment] 2021-01-31 11:57
I've updated to 1.25.2 but same error

**Comment by sebbl2** [comment] 2021-01-31 12:01
For me it worked. Although i deleted the previous version Incl.data

**Comment by adrensnyder** [comment] 2021-01-31 12:02
> For me it worked. Although i deleted the previous version Incl.data

Where is this file? Thanks

**Comment by sebbl2** [comment] 2021-01-31 12:04
What do you mean. Uninstall it in Octoprint. Afterward reinstall it. It might be shown in the plugin manager as 1.25.0/1 but after its de-zipped its 1.25.2

**Comment by sebbl2** [comment] 2021-01-31 12:05
it will download the latest master, wich is 1.25.2

**Comment by adrensnyder** [comment] 2021-01-31 12:06
> What do you mean. Uninstall it in Octoprint. Afterward reinstall it. It might be shown in the plugin manager as 1.25.0/1 but after its de-zipped its 1.25.2

I've already updated to 1.25.2 but same error. Now i try to remove completely and reinstall it

**Comment by adrensnyder** [comment] 2021-01-31 12:10
Nope. I've removed the plugin and clean data. Reinstalled and reuploaded the gcode and no Layers found:
![image](https://user-images.githubusercontent.com/15196904/106383343-a3a2e180-63c5-11eb-9059-a8413bc7e7ad.png)
![image](https://user-images.githubusercontent.com/15196904/106383351-af8ea380-63c5-11eb-8e41-eaefe7fef953.png)
![image](https://user-images.githubusercontent.com/15196904/106383364-ba493880-63c5-11eb-84cc-2f54d32efd4c.png)

What i'm doing wrong?

**Comment by sebbl2** [comment] 2021-01-31 12:15
I did not change any settings either. Did you transfer the file to OP with the the buggy plugin installed ? Maybe just delete the g-code-file and transfer it again.

**Comment by adrensnyder** [comment] 2021-01-31 12:15
> I did not change any settings either. Did you transfer the file to OP with the the buggy plugin installed ? Maybe just delete the g-code-file and transfer it again.

I've created another gcode and i've uploaded it after remove and reinstall

**Comment by sebbl2** [comment] 2021-01-31 12:25
Ok. My fault.....isnt working here neither. The pre-update g-codes still show layer progress. Since update same error as @adrensnyder. Sorry just recognized yet.

**Comment by sebbl2** [comment] 2021-01-31 12:44
@adrensnyder 
meanwhile you can go back to 1.24 
`pip install "https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/releases/download/1.24.0/master.zip"`
or
`~/oprint/bin/pip install "https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/releases/download/1.24.0/master.zip"`
or

**Comment by adrensnyder** [comment] 2021-01-31 12:48
> @adrensnyder
> meanwhile you can go back to 1.24
> `pip install "https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/releases/download/1.24.0/master.zip"`
> or
> `~/oprint/bin/pip install "https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/releases/download/1.24.0/master.zip"`
> or

Thanks for this. I was searching for it 😃

**Comment by neilbunn** [comment] 2021-02-02 19:16
I'm still getting the same error as above, using Prusa Slicer 2.3, latest Octoprint, and the 1.25.3 version, also using a Prusa MK3S. Did something change in how Prusa comments the code to trigger this? Unfortunately I updated the slicer, and Octoprint all on the same day! <laugh>

**Comment by OllisGit** [comment] 2021-02-02 20:47
Hi @neilbunn,

please provide the octoprint.log and also the file directly generate by your slicer, so that I am able to reproduce the issue with the latest version of DLP.

**Comment by neilbunn** [comment] 2021-02-02 22:48
> Hi @neilbunn,
> 
> please provide the octoprint.log and also the file directly generate by your slicer, so that I am able to reproduce the issue with the latest version of DLP.

Attached. Thanks for all you do an a great plugin, I've loved it so I hope this helps with this error. May entirely be on the user side though, but I haven't done anything other than the Prusa Slicer upgrade and the Octoprint/DLP upgrade in the last week. Was working fine before that.

[octoprint.log](https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/files/5914856/octoprint.log)
[Arc-Reactor-Ring1-Ring2-Top-Battery_0.15mm_PLA_MK3S_8h50m (1).gcode.zip](https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/files/5914858/Arc-Reactor-Ring1-Ring2-Top-Battery_0.15mm_PLA_MK3S_8h50m.1.gcode.zip)

**Comment by phealy** [comment] 2021-02-04 12:41
I suspect this might be related - when I upload a file directly into a folder (using foldername/filename.gcode in PrusaSlicer), the actual gcode goes into the correct place, but an additional file with the comments from this plugin ends up in the root of the uploads folder. This is on OctoPrint 1.5.3 running with Python 3.9.1 and plugin version 1.25.3.

[prusaslicer_export.txt](https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/files/5925709/prusaslicer_export.txt)

[file_in_upload_root.txt](https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/files/5925707/file_in_upload_root.txt)

[processed_file_in_folder.txt](https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/files/5925708/processed_file_in_folder.txt)

**Comment by OllisGit** [comment] 2021-02-07 18:22
Hi @phealy, this is related to issue #208, #207

**Comment by Daskew78** [comment] 2021-02-22 18:58
Having the same issue here also. Had to revert back.

**Comment by OllisGit** [comment] 2021-02-28 18:42
Hi @Daskew78,

which version of DLP do you use? 

Hi @phealy,
is it fixed for you?

**Comment by achampion** [comment] 2021-03-03 03:46
Continues in 1.25.4.  
OctoPrint 1.5.3. 
Cura slicer 4.8. 

Looking at the gcode created by Cura shows:
```
...
;LAYER_COUNT:348
;LAYER:0
M107
...
```

**Comment by phealy** [comment] 2021-03-04 12:17
> Hi @phealy,
> is it fixed for you?

It's resolved, thanks!

**Comment by Daskew78** [comment] 2021-03-04 13:23
> Hi @Daskew78,
> 
> which version of DLP do you use?
> 
> Hi @phealy,
> is it fixed for you?

Hi, I was using 1.25.1 but had to revert back for now.

**Comment by LightningShark25** [comment] 2021-03-24 21:20
New user to DLP.  Experiencing the same issue.  
DLP  1.25.4

Here is a snippet from my GCODE
G1 X186.267 Y36.263 E0.00461 ; infill
;LAYER_CHANGE
;Z:0.8
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0
;0.8

Here is my DLP layer change patterns...
![image](https://user-images.githubusercontent.com/79340535/112384759-a8479e80-8d53-11eb-8927-0de82770a931.png)

**Comment by OllisGit** [comment] 2021-04-04 15:34
Hi @LightningShark25,

please provide the full gcode and also the expression textarea-content instead of an image. With the image I could not reproduce the issue, btw. did you modify the default expression?

Hi @Daskew78,
which version of DLP is working for you?

**Comment by LightningShark25** [comment] 2021-04-07 09:12
Hi sorry for the delay.

I had not modified the settings no. They were as standard
HOWEVER it is now working.

As far as I can tell I didn't change anything so not sure what happened

I had restarted the octoprint a couple of times when it wasn't.

Thanks for your time

**Closed** 2021-05-18 05:02 UTC
Labels: status: markedForAutoClose, status: waitingForTestFeedback, type: bug
