### ISSUE TITLE
V1.16&V1.17  height calculation issue

### ISSUE THREAD

**Issue by GFernet** [OllisGit/OctoPrint-DisplayLayerProgress#107] opened 2020-01-21 09:05 UTC
Hello since V1.16 and 1.17 the plugin does not know the maximal height of a print and show 0.0mm
![image](https://user-images.githubusercontent.com/60132216/72790142-4c582600-3c35-11ea-9b6d-227fb7c65ecf.png)
I use a prusa MK3s printer, and check the maximum height using Max Z-Value with Extrusion on Z-Layer.

Is there any change to calculate the height between this two version and the previous one V1.15 which work great.

Thanks

**Comment by OllisGit** [comment] 2020-01-21 09:19
Hi @GFernet,
please attach you gcode (downloaded from OctoPrint) to this issue, so that I can try to reproduce the error.
Thx, in advance
Olli

**Comment by GFernet** [comment] 2020-01-21 09:22
Hi,
My GCode below, but it is the same issue on different files.
[Validation prototype force - Partie fixe_0.2mm_PLA_MK3S_2h41m.gcode.zip](https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/files/4090179/Validation.prototype.force.-.Partie.fixe_0.2mm_PLA_MK3S_2h41m.gcode.zip)

**Comment by OllisGit** [comment] 2020-01-21 09:42
Hi @GFernet ,

short info: I can reproduce the error with your gcode. I will start analysing asap.

**Comment by 9anSan5** [comment] 2020-01-22 12:11
I don't know if my problem is correlated to this one because i noticed it only with last 1.117 version. With last version octoprint ignore a lot of gcode start code of my file sliced with cura 4.4.1. The real problem is that now starts printing from an incorrect (too high) z offset.

**Comment by OllisGit** [comment] 2020-01-26 18:47
Hi @9anSan5,
thats strange!

Please provide the gcode file from cura (save to file) and also the uploaded gcode from octoprint (use download-button i octoprint next to the filename).

Thx, in advance
Olli

**Comment by OllisGit** [comment] 2020-01-28 21:17
Hi all,
I could identified the issue and it will be fixed in next release.

**Comment by OllisGit** [comment] 2020-01-30 18:46
Hi @GFernet, @9anSan5 
new Version 1.17.1 is out. 

Please test and give feedback!

Thx, in advance
Olli

**Comment by 9anSan5** [comment] 2020-01-31 21:11
Perfect, now everything is working. Thanks

**Closed** 2020-02-01 07:11 UTC
Labels: type: bug
